name: example server

on:

  push:
    branches:
      - master
      - develop
    paths:
      - 'docker/example-server/resources/server/**'

  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'docker/example-server/resources/server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: maven
        cache-dependency-path: docker/example-server/resources/server/pom.xml

    - name: Build with Maven
      run: cd docker/example-server/resources/server && mvn -B package --file pom.xml
